version: '3'

services:
  nginx:
    image: nginx:1.19.3-alpine
    container_name: sportyshop_nginx
    restart: always
    working_dir: /app
    volumes:
      - ./:/app/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_EXPOSED_PORT:-0}:80
    depends_on:
      - php

  php:
    build: ./docker/php/fpm
    restart: always
    container_name: sportyshop_php
    working_dir: /app
    volumes:
      - ./:/app/
      - ~/.ssh/:/root/.ssh/
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7.32
    container_name: sportyshop_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql

  redis:
    image: redis:6.0.9-alpine3.12
    restart: always
    container_name: sportyshop_redis
    ports:
      - 6379
